export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_ERROR = 'FETCH_PHONES_ERROR';
export const FETCH_PHONE_SUCCESS = 'FETCH_PHONE_SUCCESS';

export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS';
export const LOAD_MORE_PHONES_ERROR = 'LOAD_MORE_PHONES_ERROR';

export const PHONE_ADDED_TO_BASKET = 'PHONE_ADDED_TO_BASKET';